### ISSUE TITLE
How can I load image of toast-ui.vue-image-editor from toDataURL() string ?

### ISSUE THREAD

**Issue by naveenkumarmark** [nhn/toast-ui.vue-image-editor#23]
## Version
"@toast-ui/vue-image-editor": "^1.0.2"

## Development Environment
Chrome Version 76.0, Windows 10

## Current Behavior
Not able to create ` toast-ui.vue-image-editor ` items  from ` toDataURL() ` string

```js
const uiElements = this.$refs.tuiImageEditor.invoke('toDataURL')

// This uiElements returns the string as something like this data:image/png;base64,iVBORw0KGgoAAAANS...
```

## Expected Behavior
I want to know the method to convert the string to again ` toast-ui.vue-image-editor  ` image 
and load image again in the ` toast-ui.vue-image-editor ` for editing.
What is the method or way to do this?

Hi @junghwan-park and @jinwoo-kim-nhn
Is there any possibility to do this?

**Comment by naveenkumarmark** [comment]
I solved this issue by loading the base64 string in the 
```
loadImage: {
 path: mybase64string,
 name: 'my image name'
}

```

**Comment by AkshayMhatre** [comment]
this.$refs.tuiImageEditor.invoke('loadImageFromURL', this.testimage , 'Image name 2020');

I'm using a base64 image declared in data() but when the above line is executed in created(), it says invoke of undefined, I'm tring to load image from an external source which will send me base64.
