### ISSUE TITLE
Color palette doesn't show

### ISSUE THREAD

**Issue by SylvanoTombo** [nhn/toast-ui.vue-image-editor#26]
Hi,
The color palette in free drawing doesn't appear or small size
I dont know how to reproduce the issue
![Screenshot_2019-11-07_12-13-47](https://user-images.githubusercontent.com/40351002/68375712-631fce00-0158-11ea-9620-80ad2a4a0050.png)

**Comment by b9techsrc** [comment]
Having the same issue

**Comment by b9techsrc** [comment]
@SylvanoTombo I was able to solve this by going to the [demo site](https://ui.toast.com/tui-image-editor/) : view source and take the css from it for the TOAST UI Color Picker and the tui-image-editor.js it's all commented. Apply that to your page and it should work. It did for me

**Comment by SylvanoTombo** [comment]
> @SylvanoTombo I was able to solve this by going to the [demo site](https://ui.toast.com/tui-image-editor/) : view source and take the css from it for the TOAST UI Color Picker and the tui-image-editor.js it's all commented. Apply that to your page and it should work. It did for me

Thanks

**Comment by tbyte80** [comment]
I had the same problem. If you are using npm you can also just import the css.
`    import 'tui-color-picker/dist/tui-color-picker.css';`

**Comment by swtalk** [comment]
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
박시우(viewrain@nhn.com) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
박시우(viewrain@nhn.com) 
          
          
            * 발송 시간 : 
2020-10-28T01:18:41
          
          
            * 메일 제목 : 
Re: [nhn/toast-ui.vue-image-editor] Color palette doesn't show (#26)
          
          
            
              
                * 실패 사유 : 
              
              
                
받는 사람이 회원님의 메일을 수신차단 하였습니다.
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          dooray@nhn.com
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.
