### ISSUE TITLE
I am unable to install v1.1.0 as NPM still references v1.0.2

### ISSUE THREAD

**Issue by nickeblewis** [nhn/toast-ui.vue-image-editor#27]
## Version
v1.0.2

## Development Environment
Windows, Chrome and Firefox

## Current Behavior
I am unable to install v1.1.0 as NPM still references v1.0.2 and an older version of the TUI image editor as a result (tui-image-editor@3.3.1)

## Expected Behavior
I want to be able to install v1.1.0 which comes bundled with "tui-image-editor": "^3.7.0"
I had a look at https://www.npmjs.com/package/@toast-ui/vue-image-editor and the version there is 1.0.2 but Github refers to a newer version??

Thanks in advance!

**Comment by jinwoo-kim-nhn** [comment]
@nickeblewis We recommend that you use 1.2.0.
