### ISSUE TITLE
Remove 'postinstall' script from package.json.

### ISSUE THREAD

**Issue by alvarobrey** [nhn/toast-ui.vue-image-editor#30]
This has already been reported in the main tui.image-editor repo: https://github.com/nhn/tui.image-editor/issues/286. However, this repo (the vue wrapper) also has that script: (https://github.com/nhn/toast-ui.vue-image-editor/blob/master/package.json#L14)

In order to fix this, and allow people with Yarn (such as me!) to use the vue wrapper, you should:
* Update the tui-image-editor version in dependencies
* Remove the `postinstall` script
* Make a release

**Comment by jinwoo-kim-nhn** [comment]
Updated to v1.2.0
